name: cluster_tagebuch
description: A new Flutter project.

version: 1.1.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^1.3.1+2
  path: ^1.7.0
  path_provider: ^1.6.14
  barcode_scan: ^3.0.1
  qr_flutter: ^3.2.0
  sticky_grouped_list: ^1.2.0
  search_page: ^1.3.0
  flutter_local_notifications: ^2.0.1
  shared_preferences: ^0.5.12+2
  url_launcher: ^5.7.5
  permission_handler: ^5.0.1+1
  contacts_service: ^0.4.6
  printing: ^3.6.4

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.1.9

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/Cluster_Tagebuch_Icon.png"

flutter_native_splash:
  image: assets/icon/Cluster_Tagebuch_Icon_alpha.png
  color: "009688"
  android_disable_fullscreen: true

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/OpenSans-Regular.ttf
    - assets/icon/Cluster_Tagebuch_Icon.png
